#!/usr/bin/python3

import os
import models
from datetime import datetime
from datetime import time
import unittest
from models.base_model import BaseModel

class TestBaseModelStrMethod(unittest.TestCase):
    def setUp(self):
        self.base_model = BaseModel()

    def test_str_with_default_instance(self):
        expected = "[BaseModel] ({}) {}".format(
        self.base_model.id, self.base_model.__dict__
        )
        self.assertEqual(str(self.base_model), expected)

    def test_str_with_attributes(self):
        self.base_model.name = "Test Name"
        self.base_model.number = 42
        expected = "[BaseModel] ({}) {}".format(self.base_model.id, self.base_model.__dict__)
        self.assertEqual(str(self.base_model), expected)

    def test_str_output_type(self):
        self.assertIsInstance(str(self.base_model), str)

    def test_str_after_update(self):
        initial = str(self.base_model)
        self.base_model.name = "Updated Name"
        updated = str(self.base_model)
        self.assertNotEqual(initial, updated)

    def test_str_after_delete(self):
        self.base_model.name = "Test Name"
        initial = str(self.base_model)
        del self.base_model.name
        updated = str(self.base_model)
        self.assertNotEqual(initial, updated)

    def test_str_with_special_characters(self):
        self.base_model.special = "!@#$%^&*()"
        expected = "[BaseModel] ({}) {}".format(self.base_model.id, self.base_model.__dict__)
        self.assertEqual(str(self.base_model), expected)

    def test_str_with_multiple_attributes(self):
        self.base_model.attr1 = "value1"
        self.base_model.attr2 = "value2"
        expected = "[BaseModel] ({}) {}".format(self.base_model.id, self.base_model.__dict__)
        self.assertEqual(str(self.base_model), expected)

    def test_str_with_datetime_attributes(self):
        self.base_model.created_at = "2023-08-15T12:00:00.000000"
        self.base_model.updated_at = "2023-08-15T12:30:00.000000"
        expected = "[BaseModel] ({}) {}".format(self.base_model.id, self.base_model.__dict__)
        self.assertEqual(str(self.base_model), expected)

    def test_str_with_non_string_attributes(self):
        self.base_model.number = 42
        self.base_model.boolean = True
        expected = "[BaseModel] ({}) {}".format(self.base_model.id, self.base_model.__dict__)
        self.assertEqual(str(self.base_model), expected)

if __name__ == '__main__':
    unittest.main()
